/*
 * Represents a single log entry generated by the system.
 * Log documents are created by the centralized logger for every HTTP request
 * and for explicit endpoint access events, and are used for monitoring and debugging.
 */
// models/Log.js
const mongoose = require("mongoose");

// Schema defining the structure of a log document
const LogSchema = new mongoose.Schema(
    {
        // Timestamp indicating when the log event occurred
        time: { type: Date, required: true, default: Date.now },
        service: { type: String, required: true },
        // Log severity level (e.g., info, error)
        level: { type: String, required: true }, // info / error
        method: { type: String, required: true },
        path: { type: String, required: true },
        status: { type: Number, required: true },
        message: { type: String, required: true },
        // Optional metadata for additional context (e.g., error details)
        meta: { type: Object }
    },
    { versionKey: false }
);

// Export the Log model mapped to the "logs" collection
module.exports = mongoose.model("Log", LogSchema, "logs");
